log_interval: 200,  # 生成日志的间隔
eval_interval: 1000,  # 模型保存和测试的间隔
seed: 1234,  # 随机数种子
epochs: 20000,  # 要训练的epoch轮数
learning_rate: 2e-4,  # 学习率设置
betas: [0.8, 0.99],
eps: 1e-9,
batch_size: 64,
fp16_run: true,
lr_decay: 0.999875,
segment_size: 8192,
init_lr_ratio: 1,
warmup_epochs: 0,
c_mel: 45,
c_kl: 1.0
# 如果你不了解cleaner的工作机制，请不要动symbols，这里的Unicode是与talkingface.utils.vits_utils.text.symbols.py保持一致
symbols: ["_", ",", ".", "!", "?", "-", "~", "\u2026", "N", "Q", "a", "b", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "s", "t", "u", "v", "w", "x", "y", "z", "\u0251", "\u00e6", "\u0283", "\u0291", "\u00e7", "\u026f", "\u026a", "\u0254", "\u025b", "\u0279", "\u00f0", "\u0259", "\u026b", "\u0265", "\u0278", "\u028a", "\u027e", "\u0292", "\u03b8", "\u03b2", "\u014b", "\u0266", "\u207c", "\u02b0", "`", "^", "#", "*", "=", "\u02c8", "\u02cc", "\u2192", "\u2193", "\u2191", " "]