# Enviroment Settings
gpu_id: "0"                    # (str) The id of GPU device(s).
worker: 0                       # (int) The number of workers processing the data.
use_gpu: True                   # (bool) Whether or not to use GPU.
seed: 2023                      # (int) Random seed.
checkpoint_dir: 'saved'         # (str) The path to save checkpoint file.
show_progress: True             # (bool) Whether or not to show the progress bar of every epoch. 
log_wandb: False                # (bool) Whether or not to use Weights & Biases(W&B).
shuffle: True                   # (bool) Whether or not to shuffle the training data before each epoch.
device: 'cuda'
reproducibility: True           # (bool) Whether or not to make results reproducible.

# Training Settings
epochs: 300                     # (int) The number of training epochs.
train_batch_size: 2048          # (int) The training batch size.
learner: adam                   # (str) The name of used optimizer.
learning_rate: 0.0001            # (float) Learning rate.
eval_step: 1                    # (int) The number of training epochs before an evaluation on the valid dataset.
stopping_step: 10               # (int) The threshold for validation-based early stopping.
weight_decay: 0.0               # (float) The weight decay value (L2 penalty) for optimizers.
saved: True
resume: True
train: True

# Evaluation Settings
metrics: ["LSE", "SSIM"]
evaluate_batch_size: 50          # (int) The evaluation batch size.
lse_checkpoint_path: 'checkpoints/LSE/syncnet_v2.model'
temp_dir: 'results/temp'
lse_reference_dir: 'lse'
valid_metric_bigger: False       # (bool) Whether to take a bigger valid metric value as a better result.