---
n_feats: 80
sampling_rate: 22050
n_fft: 1024
hop_size: 256
channels: 192
filters: 768
layers: 6
kernel: 3
dropout: 0.1
heads: 2
window_size: 4
enc_dim: 128
dec_dim: 256
spk_dim: 128
use_ref_t: True
beta_min: 0.05
beta_max: 20.0
random_seed: 37
test_size: 1
train_frame: 128
data_dir: 'dataset/diffvc_data/'
val_file: "dataset/diffvc_data/filelist/valid.txt"  # 注意：修复了注释位置dataset/diffvc_data/filelist/valid.txt
exc_file: "dataset/diffvc_data/filelist/exceptions_libritts.txt"  # 注意：修复了注释位置
log_dir: 'logs_dec'
enc_dir: 'logs_enc'
epochs: 10
batch_size: 32
learning_rate: 1e-4
save_every: 1

# Train
checkpoint_sub_dir: "/diffvc" # 和overall.yaml里checkpoint_dir拼起来作为最终目录

temp_sub_dir: "/diffvc" # 和overall.yaml里temp_dir拼起来作为最终目录

train_filelist: 'dataset/diff_data/filelist/valid.txt' # 当前数据集的数据划分文件 train
test_filelist: '' # 当前数据集的数据划分文件 test
val_filelist: '' # 当前数据集的数据划分文件 val