model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm_talking.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: audio
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 9
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 128
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: ./models/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config_audio:
      target: ldm.modules.encoders.modules.AudioNet
      params:
        dim_aud: 64
        win_size: 16
    cond_stage_config_audio_smooth:
      target: ldm.modules.encoders.modules.AudioAttNet
      params:
        dim_aud: 32
    cond_stage_config_ldm:
      target: ldm.modules.encoders.modules.LdmNet
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 12
    wrap: false
    train:
      target: ldm.data.talk_data_ref_smooth_inference.TalkTrain
      params:
        size: 256
    validation:
      target: ldm.data.talk_data_ref_smooth_inference.TalkValidation
      params:
        size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    gradient_clip_val: 0.1